-- Dish ratings and user taste portrait
-- Enables users to rate recipes and generate AI-powered taste profiles

-- ── dish_ratings ──────────────────────────────────────────────────────────────
-- User ratings for recipes. One row per user per recipe.
-- Rating: 1-5 stars, with optional comment.
CREATE TABLE IF NOT EXISTS public.dish_ratings (
  id                UUID          PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id           UUID          NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  recipe_id         UUID          NOT NULL REFERENCES public.recipes(id) ON DELETE CASCADE,
  rating            INTEGER       NOT NULL CHECK (rating >= 1 AND rating <= 5),
  comment           TEXT,
  rated_at          TIMESTAMPTZ   NOT NULL DEFAULT now(),
  CONSTRAINT dish_ratings_user_recipe_key UNIQUE (user_id, recipe_id)
);

CREATE INDEX IF NOT EXISTS dish_ratings_user_idx
  ON public.dish_ratings (user_id);

CREATE INDEX IF NOT EXISTS dish_ratings_recipe_idx
  ON public.dish_ratings (recipe_id);

ALTER TABLE public.dish_ratings ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can manage their own dish ratings"
  ON public.dish_ratings FOR ALL
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

-- ── user_taste_portrait ───────────────────────────────────────────────────────
-- AI-generated taste profile for each user.
-- Generated by Gigachat based on user's health profile, meal history, and ratings.
-- portrait_data: {
--   "taste_profile_summary": "string",
--   "preferred_cuisines": ["string"],
--   "flavor_preferences": ["string"],
--   "dietary_fit": "string",
--   "health_alignment": "string",
--   "top_rated_patterns": ["string"],
--   "recommendations": ["string"]
-- }
CREATE TABLE IF NOT EXISTS public.user_taste_portrait (
  id                UUID          PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id           UUID          NOT NULL UNIQUE REFERENCES auth.users(id) ON DELETE CASCADE,
  portrait_data     JSONB         NOT NULL DEFAULT '{}',
  generated_at      TIMESTAMPTZ   NOT NULL DEFAULT now(),
  updated_at        TIMESTAMPTZ   NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS user_taste_portrait_user_idx
  ON public.user_taste_portrait (user_id);

ALTER TABLE public.user_taste_portrait ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their own taste portrait"
  ON public.user_taste_portrait FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can update their own taste portrait"
  ON public.user_taste_portrait FOR UPDATE
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

CREATE OR REPLACE FUNCTION handle_user_taste_portrait_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER set_user_taste_portrait_updated_at
  BEFORE UPDATE ON public.user_taste_portrait
  FOR EACH ROW EXECUTE FUNCTION handle_user_taste_portrait_updated_at();
